// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeTBozsvB3j23a1IEAeTjtFo1BwVGP-bA',
    appId: '1:450975758480:android:d7ccf2557aef61ce488015',
    messagingSenderId: '450975758480',
    projectId: 'vehicledispatchapp',
    storageBucket: 'vehicledispatchapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeVwL8xJDgTW0oWOUqQMLvhGpT3ZROHZ0',
    appId: '1:450975758480:ios:42f54e5332224f62488015',
    messagingSenderId: '450975758480',
    projectId: 'vehicledispatchapp',
    storageBucket: 'vehicledispatchapp.appspot.com',
    iosBundleId: 'com.example.jobhubV1',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvecCe79Fsjdoc533yRr6UkZKNrtZYgnI',
    appId: '1:450975758480:web:42e47ae3779f6637488015',
    messagingSenderId: '450975758480',
    projectId: 'vehicledispatchapp',
    authDomain: 'vehicledispatchapp.firebaseapp.com',
    storageBucket: 'vehicledispatchapp.appspot.com',
    measurementId: 'G-V91DMSS44Q',
  );

}