// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQwbwfMbYPUqsXaM7b3xGcsAKtN8JKO9E',
    appId: '1:438442066203:android:e62bd996fcdfa6150513be',
    messagingSenderId: '438442066203',
    projectId: 'wilinxhub',
    storageBucket: 'wilinxhub.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0Xm3XiKALFWP2D2fioxx3hjydJADe0Ec',
    appId: '1:438442066203:ios:2e1194f32139f9070513be',
    messagingSenderId: '438442066203',
    projectId: 'wilinxhub',
    storageBucket: 'wilinxhub.appspot.com',
    androidClientId:
        '438442066203-md1gclmtvskmep1olr0u29k5ru244qm8.apps.googleusercontent.com',
    iosClientId:
        '438442066203-v9khert0pi45es2bqu4ppg84q31r9ffo.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobhubV1',
  );
}
